# Generated by Django 4.0.2 on 2022-02-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_projects_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project',
            field=models.TextField(max_length=700),
        ),
    ]
