# Generated by Django 4.0.2 on 2022-02-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_geeksmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Biography',
        ),
        migrations.RenameModel(
            old_name='GeeksModel',
            new_name='Projects_photos',
        ),
    ]
