# Generated by Django 4.0.2 on 2022-02-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_projects_biography_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects_photos',
            name='geeks_field',
        ),
        migrations.AddField(
            model_name='projects_photos',
            name='image_field',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects_photos',
            name='image_title',
            field=models.CharField(default='hd', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='projects_photos',
            table='myapp_image',
        ),
    ]
