# Generated by Django 4.0.2 on 2022-02-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_projects_photos_geeks_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects_photos',
            name='describtion',
            field=models.TextField(default='#', max_length=100),
            preserve_default=False,
        ),
    ]
