# Generated by Django 4.0.2 on 2022-02-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_projects_photos_describtion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects_photos',
            name='describtion',
            field=models.TextField(max_length=300),
        ),
    ]
