# Generated by Django 4.0.2 on 2022-02-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_projects_photos_describtion'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects_photos',
            name='link',
            field=models.CharField(default='#', max_length=50),
            preserve_default=False,
        ),
    ]
