# Generated by Django 4.0.2 on 2022-03-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_projects_photos_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publications_photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=50)),
                ('image_field', models.ImageField(upload_to='images')),
                ('describtion', models.TextField(max_length=300)),
                ('link', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'myapp_image2',
            },
        ),
    ]
