# Generated by Django 4.0.2 on 2022-03-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_publications_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='images')),
                ('position', models.CharField(max_length=50)),
                ('github_link', models.CharField(max_length=500)),
                ('linkedin_link', models.CharField(max_length=500)),
                ('email_link', models.CharField(max_length=500)),
                ('twitter_link', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'myapp_image3',
            },
        ),
    ]
