# Generated by Django 4.0.2 on 2022-03-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='cv_link',
            field=models.CharField(default='#', max_length=500),
            preserve_default=False,
        ),
    ]
